### ISSUE TITLE
编辑器把图形缩放到足够小时，再次选中图形未显示编辑器的交互按钮

### ISSUE THREAD

**Issue by MeetTheBest** [leaferjs/leafer-in#2]
图形缩放到足够小时，再次选中图形不会出现编辑器的交互按钮，表现如下：
![Oct-12-2024 15-08-45](https://github.com/user-attachments/assets/d8c74228-0bcb-4b04-8601-03a9d8ffb227)

[复现地址](https://cloudstudio.net/a/22007978593161216?channel=share&sharetype=URL)

**Comment by leaferjs** [comment]
可以设置编辑器的config.hideOnSmall ：https://www.leaferjs.com/ui/plugin/in/editor/config.html#hideonsmall-boolean-number
